version: '3.3'
services:
  under_construction:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: site-underconstruction
    restart: unless-stopped
    ports:
      - 3000:3000